"""`ccstory init` — write ~/.ccstory/config.toml from rule-based bucket
classification of recent project folders.

No LLM call. Pure stdlib + the existing keyword classifier in
`categorizer.py`. Users tune the result by editing config.toml directly.

Flow:
  1. Scan sessions in the past N days (default 30) for projects in use.
  2. Apply the default rule-based classifier to each normalized leaf.
  3. Show the proposal, confirm, then back up + write config.toml.
"""

from __future__ import annotations

import json
import logging
import shutil
import time
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm
from rich.table import Table

from .categorizer import (
    CONFIG_PATH,
    classify,
    color_for,
    load_rules,
    normalize_project_name,
)
from .time_tracking import collect_sessions

LOG = logging.getLogger("ccstory.init")


def _collect_project_leaves(days: int) -> dict[str, int]:
    """Return {normalized_leaf: session_count} for sessions in the past N days."""
    since = datetime.now() - timedelta(days=days)
    sessions = collect_sessions(since)
    counts: dict[str, int] = defaultdict(int)
    for s in sessions:
        leaf = normalize_project_name(s.project) or s.project
        counts[leaf] += 1
    return dict(counts)


def _propose(leaves: dict[str, int]) -> dict[str, list[str]]:
    """Group leaves by their rule-based bucket. Output: {bucket: [leaf, ...]}."""
    rules = load_rules()
    proposal: dict[str, list[str]] = defaultdict(list)
    for leaf in leaves:
        bucket = classify(leaf, rules)
        proposal[bucket].append(leaf)
    return {b: sorted(set(ls)) for b, ls in proposal.items()}


def _render_proposal(console: Console, proposal: dict[str, list[str]],
                     leaves: dict[str, int]) -> None:
    table = Table(title="Rule-based bucket proposal", title_style="bold")
    table.add_column("Bucket", style="bold")
    table.add_column("Count", justify="right")
    table.add_column("Projects", style="dim")
    for bucket, projects in sorted(proposal.items(), key=lambda kv: -len(kv[1])):
        color = color_for(bucket)
        table.add_row(
            f"[{color}]{bucket}[/{color}]",
            str(len(projects)),
            ", ".join(projects),
        )
    console.print(table)


def _write_config(path: Path, proposal: dict[str, list[str]]) -> Path | None:
    """Backup existing then write new config. Returns backup path if any."""
    backup: Path | None = None
    if path.exists():
        backup = path.with_suffix(f".toml.bak-{int(time.time())}")
        shutil.copy2(path, backup)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# ccstory category overrides — generated by `ccstory init`",
        "# Backup of previous config (if any) saved alongside this file.",
        "#",
        "# Built-in defaults: coding, investment, writing, other.",
        "# Unmatched projects fall back to `coding`.",
        "",
        "[categories]",
    ]
    for bucket, projects in sorted(proposal.items(), key=lambda kv: -len(kv[1])):
        plist = ", ".join(json.dumps(p) for p in projects)
        lines.append(f'"{bucket}" = [{plist}]')
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return backup


def run_init(days: int = 30, dry_run: bool = False,
             auto_yes: bool = False, console: Console | None = None) -> int:
    """Entry point invoked by `ccstory init`. No LLM call."""
    console = console or Console()

    console.print(
        f"[bold]Scanning past {days} days of sessions…[/bold]"
    )
    leaves = _collect_project_leaves(days)
    if not leaves:
        console.print("[yellow]No engaged sessions found.[/yellow] "
                      "Use Claude Code for a while, then re-run init.")
        return 0
    console.print(
        f"[green]✓[/green] Found {len(leaves)} unique projects.\n"
    )

    proposal = _propose(leaves)
    _render_proposal(console, proposal, leaves)
    console.print(
        f"\n[dim]Existing config: {CONFIG_PATH} "
        f"({'will be backed up' if CONFIG_PATH.exists() else 'not present yet'})[/dim]"
    )

    if dry_run:
        console.print("\n[dim]--dry-run set, not writing.[/dim]")
        return 0
    if not auto_yes:
        if not Confirm.ask("\nWrite this to ~/.ccstory/config.toml?",
                           console=console, default=True):
            console.print("[yellow]Skipped.[/yellow]")
            return 0

    backup = _write_config(CONFIG_PATH, proposal)
    console.print(
        f"\n[green]✓[/green] Wrote {CONFIG_PATH}"
        + (f"  [dim](backup: {backup.name})[/dim]" if backup else "")
    )
    console.print(
        "[dim]Tune buckets by editing the file. "
        "Re-run `ccstory week` to see the new categorization.[/dim]"
    )
    return 0
